name: comic_text_yofardev
description: Add bubbles to your comics

publish_to: "none"

version: 2.0.2+4

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # To manage multiple languages
  flutter_localizations:
    sdk: flutter
  # To cache image from network
  cached_network_image:
  # Zoom and pan image View
  photo_view:
  # Shared pref
  shared_preferences:
  # To get size of a widget
  measured_size:
  # Csv
  csv: ^6.0.0
  # Screenshot
  screenshot:
  # File picker
  file_picker: ^8.0.3
  universal_io:
  # Parsed text
  flutter_parsed_text:
  # Uuid
  uuid: ^4.5.1
  # Color picker
  flutter_colorpicker:
  image: ^4.5.4
  # Youtube player
  youtube_player_iframe:
  url_launcher: ^6.2.6
  web: ^0.5.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint:

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: BottleRocket
      fonts:
        - asset: assets/fonts/BottleRocket.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Manga
      fonts:
        - asset: assets/fonts/mangat.ttf
    - family: Anime
      fonts:
        - asset: assets/fonts/animeace2_reg.otf
    - family: Badaboom
      fonts:
        - asset: assets/fonts/BadaboomBB_Reg.otf
    - family: FuturaHandwritten
      fonts:
        - asset: assets/fonts/FuturaHandwritten.ttf
